import type { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { client } from '../services/prismicClient'
import useSWR from 'swr'
import ButtonSolid from '../components/Buttons/ButtonSolid'
import ButtonOutline from '../components/Buttons/ButtonOutline'
import Container from '../components/Partials/Container'

// type inferedTypes = InferGetStaticPropsType<typeof getStaticProps>

const Home: NextPage = () => {
  const { data: bannersHome } = useSWR('banners_da_home', () =>
    client.getSingle('banners_da_home')
  )

  return (
    <div>
      <Head>
        <title>PCS UFPA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Container>
          <div className="grid grid-cols-5 mt-20">
            <div className="col-span-3 border-r border-zinc-100 pr-5">
              <header className="flex border-b border-zinc-200">
                <span className="p-3 font-light cursor-pointer border-b-2 border-black">
                  Blog
                </span>
                <span className="p-3 font-light cursor-pointer">Eventos</span>
                <span className="p-3 font-light cursor-pointer">Arquivos</span>
                <span className="p-3 font-light cursor-pointer">
                  O Conexões
                </span>
                <span className="p-3 font-light cursor-pointer">Atuações</span>
                <span className="p-3 font-light cursor-pointer">
                  Conexistas
                </span>
              </header>
              <div className='py-5'>
                <div className='hover mb-2 cursor-pointer group'>
                  <small>Angelo Ricardo - 3 de Agosto de 2023</small>
                  <h2 className="text-2xl font-bold group-hover:text-blue-900 transition-all">
                    Understanding Server Components in React 18 and Next.js 13{' '}
                  </h2>
                  <p className='font-light'>
                    With the release of Next.js 13, they have a new /app
                    directory that has newer approaches to data rendering,
                    fetching, and also ...
                  </p>
                </div>
              </div>
            </div>
            <aside className="col-span-2">Sidebar</aside>
          </div>
        </Container>
      </main>
    </div>
  )
}

export default Home
